### ISSUE TITLE
At paseto/lib/v1/sign.js

### ISSUE THREAD

**Issue by shy-Xu** [panva/paseto#39]
### What happened?

I've got a bug

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'RSA_PKCS1_PSS_PADDING')
    at node_modules/paseto/lib/v1/sign.js (sign.js:3:28)
    at __require2 (chunk-CLUHM6AE.js?v=ffcba462:19:50)
    at node_modules/paseto/lib/v1/index.js (index.js:1:14)
    at __require2 (chunk-CLUHM6AE.js?v=ffcba462:19:50)
    at node_modules/paseto/lib/index.js (index.js:2:12)
```

### Version

v3.1.2

### Node.js Version

v16.0.4

### Code to reproduce

```js
Just a simple demo, I wonder if it's due to my local environment
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/paseto/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
> I wonder if it's due to my local environment

Sure is. `RSA_PKCS1_PSS_PADDING` is an openssl constant exposed in every supported Node.js version.
