### ISSUE TITLE
Bug cannot read property 'subtle' of undefined

### ISSUE THREAD

**Issue by Spectre98** [panva/paseto#40]
### What happened?

When I try to implement paseto V4 in expressjs it gives me this error

C:\laragon\www\scirpt\node_modules\paseto\lib\help\crypto_worker.js:10
   webcrypto: { subtle },
               ^

TypeError: Cannot read property 'subtle' of undefined
     at Object.<anonymous> (C:\laragon\www\scirpt\node_modules\paseto\lib\help\crypto_worker.js:10:16)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
     at Module.load (internal/modules/cjs/loader.js:928:32)
     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
     at Module.require (internal/modules/cjs/loader.js:952:19)
     at require (internal/modules/cjs/helpers.js:88:18)
     at Object.<anonymous> (C:\laragon\www\scirpt\node_modules\paseto\lib\help\sign.js:1:18)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

### Version

v3.1.2

### Node.js Version

v16.17.0

### Code to reproduce

```js
const paseto = require('paseto')
const { V4 } = paseto
```

### Required

- [x] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/paseto/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Node's crypto module has a webcrypto property in all v16.x releases. 🤷‍♂️
